spring:
  application:
    name: _04_paging
  datasource:
    url: jdbc:mysql://localhost:3306/menudb
    username: sh
    password: sh
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 50
      max-lifetime: 60000
      minimum-idle: 5
      idle-timeout: 30000
      auto-commit: false

server:
  servlet:
    context-path: /app
logging:
  level:
    root: info
    com.sh: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.sh._04_paging.menu, com.sh._04_paging.order
  mapper-locations: classpath*:mappers/**/*-mapper.xml