spring:
  application:
    name: _06_file_upload
  servlet:
    multipart:
      max-file-size: 10MB # ??? ???
      max-request-size: 50MB # ??? ??

server:
  servlet:
    context-path: /app

logging:
  level:
    root: info
    com.sh: debug