-- 1
SELECT
    EMP_ID, EMP_NAME, PHONE, HIRE_DATE, QUIT_YN
FROM
    EMPLOYEE
WHERE
    PHONE LIKE '%2'
    AND QUIT_YN <> 'Y'
ORDER BY
    HIRE_DATE DESC
LIMIT 3;

-- 2
SELECT
    E.EMP_NAME, J.JOB_NAME, E.SALARY, E.EMP_NO, E.EMAIL, E.PHONE, E.HIRE_DATE
FROM
    EMPLOYEE E JOIN JOB J
        ON E.JOB_CODE = J.JOB_CODE
WHERE
    J.JOB_NAME = '대리'
    AND E.QUIT_YN <> 'Y'
ORDER BY
    E.SALARY DESC;

-- 3
SELECT
    D.DEPT_TITLE AS 부서명,
    COUNT(*) AS 인원,
    FORMAT(SUM(E.SALARY), 0) AS 급여합계,
    FORMAT(AVG(E.SALARY), 0) AS 급여평균
FROM
    EMPLOYEE E JOIN DEPARTMENT D
        ON E.DEPT_CODE = D.DEPT_ID
WHERE
    E.QUIT_YN <> 'Y'
GROUP BY
    D.DEPT_TITLE WITH ROLLUP;


-- 4
SELECT
    E.EMP_NAME, E.EMP_NO, E.PHONE, D.DEPT_TITLE, J.JOB_NAME
FROM
    EMPLOYEE E
        LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
        JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
ORDER BY
    E.HIRE_DATE;

-- 5
SELECT
    COUNT(*)
FROM
    EMPLOYEE
WHERE
    MANAGER_ID IS NOT NULL
ORDER BY
    EMP_NAME;

-- 6 
SELECT
    E1.EMP_NAME, E2.EMP_NAME
FROM
    EMPLOYEE E1 LEFT JOIN EMPLOYEE E2
        ON E1.MANAGER_ID = E2.EMP_ID
ORDER BY
    E1.EMP_NAME;

-- 7
SELECT
    E1.EMP_NAME, D1.DEPT_TITLE, E2.EMP_NAME, D2.DEPT_TITLE
FROM
    EMPLOYEE E1
        JOIN EMPLOYEE E2 ON E1.MANAGER_ID = E2.EMP_ID
        LEFT JOIN DEPARTMENT D1 ON E1.DEPT_CODE = D1.DEPT_ID
        LEFT JOIN DEPARTMENT D2 ON E2.DEPT_CODE = D2.DEPT_ID
ORDER BY
    E1.EMP_NAME;
