spring:
  application:
    name:_02_transaction
  datasource:
    url: jdbc:mysql://localhost:3306/menudb
    username: sh
    password: sh
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    root: info
    com.sh: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.sh
  mapper-locations: classpath*:mappers/**/*-mapper.xml
