spring:
  application:
    name: _03_spring_crud

  datasource:
    url: jdbc:mysql://localhost:3306/menudb
    username: sh
    password: sh
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 50
      max-lifetime: 60000
      minimum-idle: 5 #\uB180\uACE0 \uC788\uB294 \uC560\uAC00 10\uAC1C\uBA74 5\uAC1C\uAE4C\uC9C0 \uC904\uC5EC\uC900\uB2E4
      idle-timeout: 30000
      auto-commit: false

logging:
  level:
    root: info
    com.sh : debug


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.sh
  mapper-locations: classpath*:mappers/**/*-mapper.xml
server:
  servlet:
    context-path: /app
