spring:
  application:
    name: _06_spring_data_jpa
  datasource: # db? ???? ??
    driver-class-name: com.mysql.cj.jdbc.Driver # db??? ?? ??? ???? ?
    url: jdbc:mysql://localhost/menudb # db??? ???? ??? jdbc:mysql:// ???
    username: sh
    password: sh
  jpa: # ??? ???? jpa??
    show-sql: true
    generate-ddl: false # ?? db? ??? ???? false
    properties:
      hibernate:
        hbm2ddl:
          auto: none # ??? none?? ??. create?? ?? ?? db? ??? ? ??.
        format_sql: true # ?? ? ?? ??? ? ?? ???.(?? ???)

server:
  servlet:
    context-path: /app #app? ??? ?? ? ??. ?????? ???? ??? ??

logging:
  level:
    root: info
    com.sh.app: debug