spring:
  application:
    name: _01_spring_mybatis
  datasource:
    url: jdbc:mysql://localhost:3306/menudb
    username: sh
    password: sh
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info
    com.sh: debug

# mybatis config
#mybatis:
#  mapper-locations: classpaht:/mappers/**/*-mapper.xml