spring:
  application:
    name: _01_spring_mybatis
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/menudb
      username: sh
      password: sh
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
logging:
  level:
    root: info
    com.sh: debug
