spring:
  application:
    name: _06_spring_data_jpa

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    username: sh
    password: sh


  jpa:
    show-sql: true
    generate-ddl: false #\uAE30\uC874\uC5D0 \uC788\uB294 db\uB97C \uC4F8 \uAC70\uB77C\uC11C
    properties: # ddl\uB85C \uC4F0\uBA74 \uBC14\uB85C \uB098\uC628\uB2E4
      hibernate:
        hbm2ddl:
          auto: none
        format_sql: true # \uC774\uAC70 \uC548\uC4F0\uBA74 \uCFFC\uB9AC\uAC00 \uADF8\uB0E5 \uD55C \uC904\uB85C \uB098\uC640\uBC84\uB9B0\uB2E4 \uBCF4\uAE30 \uD798\uB4EC

logging:
  level:
    root: info
    com.sh.app: debug

server:
  servlet:
    context-path: /app
